---
- name: Verificar se o node está no cluster
  command: kubectl get nodes --no-headers
  delegate_to: "{{ groups['k8s-master'][0] }}"
  register: cluster_nodes
  changed_when: false

- name: Verificar se este node já está pronto
  set_fact:
    node_in_cluster: "{{ inventory_hostname in cluster_nodes.stdout }}"
  changed_when: false

- name: Criar token de join se node não estiver no cluster
  command: kubeadm token create --print-join-command
  delegate_to: "{{ groups['k8s-master'][0] }}"
  register: join_command
  when: not node_in_cluster

- name: Executar kubeadm join no worker
  command: "{{ join_command.stdout }} --ignore-preflight-errors=Swap"
  when: not node_in_cluster
