---
- name: Obter hostname do node
  ansible.builtin.command: hostname
  register: node_hostname
  changed_when: false

- name: Debug hostname
  debug:
    msg: "Hostname do worker detectado: {{ node_hostname.stdout }}"

- name: Verificar se o node já está no cluster
  ansible.builtin.shell: |
    kubectl get nodes --no-headers | awk '{print $1}' | grep -w "{{ node_hostname.stdout }}"
  register: node_in_cluster
  changed_when: false
  failed_when: false
  delegate_to: 192.168.0.170

- name: Debug resultado cluster
  debug:
    msg: "Resultado da checagem: stdout={{ node_in_cluster.stdout }}, rc={{ node_in_cluster.rc }}"

- name: Criar token de join se node não estiver no cluster
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_cmd
  changed_when: true
  when: node_in_cluster.rc != 0
  delegate_to: 192.168.0.170

- name: Executar kubeadm join no worker
  ansible.builtin.shell: "{{ join_cmd.stdout }} --ignore-preflight-errors=Swap"
  when: node_in_cluster.rc != 0
