---
- name: Verificar se o node já está no cluster
  ansible.builtin.shell: |
    kubectl get nodes --no-headers | grep -w "{{ inventory_hostname }}"
  register: node_in_cluster
  changed_when: false
  failed_when: false
  delegate_to: 192.168.0.170  # IP do master

- name: Verificar se o kubelet está pronto no node
  ansible.builtin.shell: |
    test -f /etc/kubernetes/kubelet.conf && echo "ready" || echo "notready"
  register: kubelet_ready
  changed_when: false

- name: Criar token de join se o node não estiver no cluster
  ansible.builtin.shell: |
    kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  changed_when: true
  delegate_to: 192.168.0.170
  when: node_in_cluster.rc != 0

- name: Executar kubeadm join no worker se necessário
  ansible.builtin.shell: |
    {{ kubeadm_join_cmd.stdout }} --ignore-preflight-errors=Swap
  when: 
    - node_in_cluster.rc != 0
    - kubelet_ready.stdout == "notready"
  register: join_result
  changed_when: true
  retries: 3
  delay: 10
  until: join_result.rc == 0