---
- name: Verificar se o node está no cluster
  shell: "kubectl get nodes --no-headers | grep -w $(hostname) || true"
  register: node_in_cluster
  delegate_to: 192.168.0.170  # IP do master
  run_once: false

- name: Criar token de join se node não estiver no cluster
  shell: kubeadm token create --print-join-command
  register: join_cmd
  delegate_to: 192.168.0.170  # IP do master
  when: node_in_cluster.stdout == ""
  run_once: false

- name: Executar kubeadm join no worker
  shell: "{{ join_cmd.stdout }} --ignore-preflight-errors=Swap"
  when: node_in_cluster.stdout == ""
  register: join_result
  retries: 3
  delay: 10
  until: join_result.rc == 0