- name: Instalar bibliotecas Python necessárias para o módulo Kubernetes
  pip:
    name:
      - kubernetes
      - openshift
    executable: pip3
  become: true
  when: inventory_hostname in groups['k8s-master']

- name: Instalar pip3 se não estiver presente
  apt:
    name: python3-pip
    state: present
  become: true
  when: inventory_hostname in groups['k8s-master']

- name: Criar namespace 'monitoring'
  command: kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
  run_once: true
  ignore_errors: yes

- name: Adicionar repositório do Prometheus Community
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  args:
    creates: /root/.cache/helm/repository/prometheus-community-index.yaml

- name: Atualizar repositórios do Helm
  command: helm repo update

- name: Copiar values.yaml para o master
  template:
    src: values.yaml.j2
    dest: /root/values.yaml

- name: Instalar kube-prometheus-stack com Helm
  command: >
    helm install monitoring prometheus-community/kube-prometheus-stack
    --namespace monitoring
    --create-namespace
    --version 58.2.0
    -f /root/values.yaml
  args:
    creates: /root/.kube-prometheus-installed
  register: helm_install_output

- name: Marcar instalação como concluída
  file:
    path: /root/.kube-prometheus-installed
    state: touch

- name: Exibir saída do Helm
  debug:
    var: helm_install_output.stdout
