---
#- name: Instalar dependências do Ansible
#  hosts: k8s-master
#  become: yes
#  roles:
#    - ansible-deps

#- name: Instalar Kubernetes nos nós do cluster
#  hosts: k8s-cluster
#  become: yes
#  roles:
#    - kubernetes

#- name: Instalar Helm no master
#  hosts: k8s-master
#  become: yes
#  roles:
#    - helm

#- name: Instalar Prometheus e Grafana no master
#  hosts: k8s-master
#  become: yes
#  roles:
#    - monitoring

- name: Habilitar containerd e kubelet na inicialização
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - containerd
    - kubelet